In [1]:
import pandas as pd
import numpy as np

In [2]:
import export_vis as m
d1 = m.init_base('pokedex.json')
d2 = m.init_draw_test(-1)
d2

                 num              name     type1   type2  base_spe
bulbasaur          1         Bulbasaur     Grass  Poison        45
ivysaur            2           Ivysaur     Grass  Poison        60
venusaur           3          Venusaur     Grass  Poison        80
charmander         4        Charmander      Fire    None        65
charmeleon         5        Charmeleon      Fire    None        80
...              ...               ...       ...     ...       ...
basculegionf     902     Basculegion-F     Water   Ghost        78
sneasler         903          Sneasler  Fighting  Poison       120
overqwil         904          Overqwil      Dark  Poison        85
enamorus         905          Enamorus     Fairy  Flying       106
enamorustherian  905  Enamorus-Therian     Fairy  Flying        46

[1053 rows x 5 columns]

In [4]:
d2.to_json('full.json', orient='records')